### ISSUE TITLE
SR04

### ISSUE THREAD

**Issue by 1RanShy** [1RanShy/Project#1]
This device's class is not well written. Don't use static member functions to write the class for this device.

**Comment by 1RanShy** [comment]
Can you just fix this in your branch? yulong

**Comment by 1RanShy** [comment]
> This device's class is not well written. Don't use static member functions to write the class for this device.

And when I make your part of the code. It seems that something is wrong.

**Comment by yulong-liu-host** [comment]
I have solve this problem. Please cheack the latest file.

**Comment by 1RanShy** [comment]
> I have solve this problem. Please cheack the latest file.

Thx, I I have already tried that. It can works properly now.
