### ISSUE TITLE
Modile App design

### ISSUE THREAD

**Issue by 1RanShy** [1RanShy/Project#4]
# New functions add
Zexuan, could you please update your mobile application code? 

I have already written the Bluetooth code for enabling and disabling the automatic feeding. The command "CAAAC" can turn on and off the automatic feeding mode. Every time the mode is switched, I will send "11111" or "22222", which respectively represent turning on and off the automatic feeding mode. 
*"CAAAC", "11111", and "22222" are all 5-digit ASCII codes.*

**Comment by Zexuan2815250** [comment]
okay, i have write a demo for your requirment. In the blue tooth page, there is a buttom responsibles for that, it cloud realize the function. I will upload asap. And now I will change the buttom style to make it more beautiful. after change, I will let you know.
